### ISSUE TITLE
22 LoS can't load

### ISSUE THREAD

**Issue by pakhomovok** [mrtozkn/jason_lineage#2]
Hi. Thank you for your work. Faced with such a problem. After installing this ROM via TWRP (LoS 22 on 15 android), the phone is not loaded into the system, but is loaded back into TWRP. What could be the problem? Thank you.
Phone Mi Note 3.

**Comment by mrtozkn** [comment]
Hello,

Can you try installing via Lineage's recovery , additionally wipe data,cache and system fresh install this steps can solve your problem.

**Comment by pakhomovok** [comment]
Thank you. It helped. But LoS recovery is quite unusual. Is it possible to change it to another one without losing data and the operating system itself? I tried to do this via adb sideload, but LoS recovery started swearing: Signature verification failed.

**Comment by mrtozkn** [comment]
Normally, If there is no significant component change in the system, there is no need to wipe. Also, you may have received this error because you did not use a signed recovery for the verification error for recovery. This is not a major problem, but if you use the recovery.img in the zip, your problem will be solved.
